# Generated by Django 2.2.4 on 2020-12-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
