# Generated by Django 2.2.4 on 2020-12-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0004_auto_20201214_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='quizes', to='quiz_api.Question'),
        ),
    ]
